apiVersion: apps/v1
kind: Deployment
metadata:
  name: wexa-ai-deployment
  labels:
    app: wexa-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wexa-ai
  template:
    metadata:
      labels:
        app: wexa-ai
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: wexa-ai
          image: ghcr.io/alw-n/wexa-ai:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
