name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          # Force lowercase for username
          LOWERCASE_USER=${{ github.repository_owner }}
          LOWERCASE_USER=${LOWERCASE_USER,,}
          IMAGE_NAME=ghcr.io/$LOWERCASE_USER/wexa-ai:latest
          echo "IMAGE_NAME=$IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          LOWERCASE_USER=${{ github.repository_owner }}
          LOWERCASE_USER=${LOWERCASE_USER,,}
          IMAGE_NAME=ghcr.io/$LOWERCASE_USER/wexa-ai:latest
          docker push $IMAGE_NAME
